plugins:
  topic_featured_link_extra_digest_email_anchor_style:
    default: "color:#737373;padding:4px 10px;border:1px solid #e6e6e6;border-radius:2px;box-shadow:0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);"
    client: false
  topic_featured_link_extra_link_ref:
    default: ''
    client: true
